spring:
  application:
    name: EnginSearchv4

  datasource:
    url: jdbc:mysql://localhost:3306/enginev2?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
app:
  storage:
    thumbnail-path: ${THUMBNAIL_PATH:/home/minaoui/Documents/web/}
    download-path: ${DOWNLOAD_PATH:/home/minaoui/Documents/web/}

server:
  port: 8081